/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    inventory: Inventory;
    vehicle_carousel: VehicleCarousel;
    pages: Page;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: string;
  featuredphoto: string;
  dealer_id: number;
  vin: string;
  status: string;
  statusoverride?: string | null;
  featured: number;
  stocknumber: string;
  location: string;
  originalprice: number;
  price: number;
  specialprice?: number | null;
  addonprice?: number | null;
  msrp?: number | null;
  year: number;
  make: string;
  model: string;
  modelnumber?: string | null;
  trim?: string | null;
  series?: string | null;
  body: string;
  condition: string;
  certified?: number | null;
  mileage: number;
  exteriorcolor?: string | null;
  interiorcolor?: string | null;
  exteriorcolorstandard?: string | null;
  interiorcolorstandard?: string | null;
  fuel: string;
  transmission?: string | null;
  transmissionstandard?: string | null;
  drivetrain: string;
  drivetrainstandard?: string | null;
  engine?: string | null;
  displacement?: number | null;
  cylinders?: number | null;
  maxhorsepower?: number | null;
  maxhorsepowerat?: number | null;
  maxtorque?: number | null;
  maxtorqueat?: number | null;
  aspiration?: string | null;
  mpgcity?: number | null;
  mpghwy?: number | null;
  doors?: number | null;
  seatingcapacity?: number | null;
  towingcapacity?: number | null;
  carfax?: {
    carfaxurl?: string | null;
    carfaxicon?: string | null;
    carfaxalt?: string | null;
    carfaxoneowner?: number | null;
    carfaxownerstext?: string | null;
    carfaxownersicon?: string | null;
    carfaxusetext?: string | null;
    carfaxuseicon?: string | null;
    carfaxservicerecords?: number | null;
    carfaxaccidenttext?: string | null;
    carfaxaccidenticon?: string | null;
    carfaxsnapshotkey?: string | null;
  };
  autocheck?: string | null;
  photocount?: number | null;
  notes?: string | null;
  incentives?: string | null;
  metatitle?: string | null;
  metadescription?: string | null;
  vehicledescription?: string | null;
  dealer?: {
    name?: string | null;
    city?: string | null;
    state?: string | null;
    phonemain?: string | null;
    capitalone_token?: string | null;
  };
  title?: string | null;
  url?: string | null;
  hot?: number | null;
  new?: number | null;
  finance?: {
    down_pct?: number | null;
    salestaxstate?: string | null;
    vehicle_amount?: number | null;
    shipping_amount?: number | null;
    tradein_amount?: number | null;
    tradein_remainingbalance?: number | null;
    down_payment?: number | null;
    doctitlefees_amount?: number | null;
    tax_amount?: number | null;
    tax_rate?: number | null;
    tax_rate_formatted?: number | null;
    tax_tradeincredit?: number | null;
    loan_amount?: number | null;
    loan_months?: number | null;
    interest_rate?: number | null;
    interest_rate_formatted?: number | null;
    credit_tier?: string | null;
    total_cost?: number | null;
    total_interest?: number | null;
    monthly_payment?: number | null;
  };
  features?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  photos?:
    | {
        src?: string | null;
        id?: string | null;
      }[]
    | null;
  video?: {
    source?: string | null;
    url?: string | null;
    autoplay?: string | null;
    aspectratio?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle_carousel".
 */
export interface VehicleCarousel {
  id: string;
  dealer_id: number;
  vin: string;
  stocknumber: string;
  originalprice: number;
  price: number;
  year: number;
  make: string;
  model: string;
  modelnumber?: string | null;
  trim?: string | null;
  series?: string | null;
  mileage: number;
  exteriorcolor?: string | null;
  interiorcolor?: string | null;
  exteriorcolorstandard?: string | null;
  interiorcolorstandard?: string | null;
  dealer?: {
    name?: string | null;
    city?: string | null;
    state?: string | null;
    phonemain?: string | null;
    capitalone_token?: string | null;
  };
  title?: string | null;
  url?: string | null;
  finance?: {
    down_pct?: number | null;
    salestaxstate?: string | null;
    vehicle_amount?: number | null;
    shipping_amount?: number | null;
    tradein_amount?: number | null;
    tradein_remainingbalance?: number | null;
    down_payment?: number | null;
    doctitlefees_amount?: number | null;
    tax_amount?: number | null;
    tax_rate?: number | null;
    tax_rate_formatted?: number | null;
    tax_tradeincredit?: number | null;
    loan_amount?: number | null;
    loan_months?: number | null;
    interest_rate?: number | null;
    interest_rate_formatted?: number | null;
    credit_tier?: string | null;
    total_cost?: number | null;
    total_interest?: number | null;
    monthly_payment?: number | null;
  };
  photos?:
    | {
        src?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  text?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'inventory';
        value: string | Inventory;
      } | null)
    | ({
        relationTo: 'vehicle_carousel';
        value: string | VehicleCarousel;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  _lastEdited: {
    user: {
      relationTo: 'users';
      value: string | User;
    };
    editedAt?: string | null;
  };
  isLocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}