export const CarCarouselData = [
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267831/image-1.webp" },
    id: 267831,
    dealer_id: 219,
    vin: "4T1B11HK6KU769501",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14408",
    location: "lot",
    originalprice: 20995,
    price: 20995,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2019,
    make: "Toyota",
    model: "Camry",
    modelnumber: "2546",
    trim: "SE",
    series: "",
    body: "Sedan",
    condition: "Pre-owned",
    certified: 0,
    mileage: 91741,
    exteriorcolor: "Midnight Black Metallic",
    interiorcolor: "Black C",
    exteriorcolorstandard: "Black",
    interiorcolorstandard: "Black",
    fuel: "Gasoline",
    transmission: "8-Speed Automatic",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "2.5L I4 DOHC 16V",
    displacement: 2.5,
    cylinders: 4,
    maxhorsepower: 203,
    maxhorsepowerat: 6600,
    maxtorque: 184,
    maxtorqueat: 5000,
    aspiration: "Naturally Aspirated",
    mpgcity: 28,
    mpghwy: 39,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: null,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/I23L_WLvA0d3r0SmLIbJ8tas56JkJ8FIT2tTX470bJ361zJ_XJviHgj53WLy3Wk3s-UuXRt9E9ZNtGIAeqjfwadaqrHilI4MHv4",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/1own.svg",
    carfaxalt: "Show Me the CARFAX 1-Owner Badge",
    carfaxoneowner: 1,
    carfaxownerstext: "CARFAX 1-Owner",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner1.svg",
    carfaxusetext: "Rental Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_rental.svg",
    carfaxservicerecords: 1,
    carfaxaccidenttext: "No Accident or Damage Reported",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_noAccident.svg",
    carfaxsnapshotkey:
      "hlEQzfNmhFW3rlSBDS0jX3MG_DC3hZkOhjBoSIcTNWmN94gKEsWitSZZ7deFD2SiiCMb9PAVKq9hh_r5raWwNvzDExcNE8nzeVQ",
    autocheck: null,
    photocount: 64,
    notes:
      "CARFAX One-Owner.\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2019 Toyota Camry. This SE Camry comes well equipped with Black C Artificial Leather.\u003cbr\u003e\u003cbr\u003eMidnight Black 2019 Toyota Camry SE 8-Speed Automatic 2.5L I4 DOHC 16V\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2019 Toyota Camry SE",
    url: "/inventory/2019-toyota-camry-se-4T1B11HK6KU769501",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 20995,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 20995,
      loan_months: 60,
      interest_rate: 0.0689,
      interest_rate_formatted: 6.89,
      credit_tier: "AA",
      total_cost: 24878.25,
      total_interest: 3883.25,
      monthly_payment: 414.64,
    },
    features: [
      {name:"Adaptive cruise control"},
      {name:"Apple CarPlay"},
      {name:"Automatic climate control"},
      {name:"Backup camera"},
      {name:"Bluetooth"},
      {name:"Collision warning"},
      {name:"Lane departure warning"},
      {name:"Lane keep assist"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267831/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267831/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267831/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267831/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267831/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267830/image-1.webp" },
    id: 267830,
    dealer_id: 219,
    vin: "5J8TC1H55KL002890",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14388",
    location: "lot",
    originalprice: 22695,
    price: 22695,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2019,
    make: "Acura",
    model: "RDX",
    modelnumber: "TC1H5KKNW",
    trim: "Technology Package",
    series: "",
    body: "SUV",
    condition: "Pre-owned",
    certified: 0,
    mileage: 69276,
    exteriorcolor: "Majestic Black Pearl",
    interiorcolor: "Espresso, Premium Le",
    exteriorcolorstandard: "Black",
    interiorcolorstandard: "--",
    fuel: "Gasoline",
    transmission: "10-Speed Automatic",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "2.0L 16V DOHC",
    displacement: 2,
    cylinders: 4,
    maxhorsepower: 272,
    maxhorsepowerat: 6500,
    maxtorque: 280,
    maxtorqueat: 1600,
    aspiration: "Turbo",
    mpgcity: 22,
    mpghwy: 28,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: 1500,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/hQuPcQP9go5p74HSS6VHdKVidCIbH09FDGpjjmSPEm6FLK4CjCoHMYKudBu0VdkysFHwPJLK5PgQMyZ9cQdnvgoju-MeG9IUvJ8",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/showme.svg",
    carfaxalt: "Show Me the CARFAX Badge",
    carfaxoneowner: 0,
    carfaxownerstext: "3+ Owners",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner3.svg",
    carfaxusetext: "Personal Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_personal.svg",
    carfaxservicerecords: 11,
    carfaxaccidenttext: "Damage Reported",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_accident.svg",
    carfaxsnapshotkey:
      "NOG6ThQU43LStOLVlWcY37KzMZMUqlSdvmkQglDwfTKFtBO14aStjpfTi2ImnHEhcaVatKsJrLuQI8Ag4dmIteMPNBfD7C4MEuU",
    autocheck: null,
    photocount: 71,
    notes:
      "Priced below KBB Fair Purchase Price! Odometer is 1102 miles below market average!\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2019 Acura RDX. This Technology Package RDX comes well equipped with .\u003cbr\u003e\u003cbr\u003eBlack Pearl 2019 Acura RDX Technology Package 10-Speed Automatic 2.0L 16V DOHC\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2019 Acura RDX Technology Package",
    url: "/inventory/2019-acura-rdx-technology-package-5J8TC1H55KL002890",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 22695,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 22695,
      loan_months: 60,
      interest_rate: 0.0689,
      interest_rate_formatted: 6.89,
      credit_tier: "AA",
      total_cost: 26892.68,
      total_interest: 4197.68,
      monthly_payment: 448.21,
    },
    features: [
      {name: "Adaptive cruise control"},
      {name: "Apple CarPlay"},
      {name: "Automatic climate control"},
      {name: "Backup camera"},
      {name: "Blind spot monitor"},
      {name: "Bluetooth"},
      {name: "Collision warning"},
      {name: "Cross traffic alert"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267830/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267830/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267830/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267830/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267830/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267826/image-1.webp" },
    id: 267826,
    dealer_id: 219,
    vin: "2C4RC1BG5FR610022",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14453",
    location: "lot",
    originalprice: 9995,
    price: 9995,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2015,
    make: "Chrysler",
    model: "Town \u0026 Country",
    modelnumber: "RTYP53",
    trim: "Touring",
    series: "",
    body: "Passenger van",
    condition: "Pre-owned",
    certified: 0,
    mileage: 98225,
    exteriorcolor: "Brilliant Black Crystal Pearlcoat",
    interiorcolor: "Black/Light Graystone",
    exteriorcolorstandard: "Black",
    interiorcolorstandard: "Black",
    fuel: "Flex Fuel",
    transmission: "6-Speed Automatic",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "V6",
    displacement: 3.6,
    cylinders: 6,
    maxhorsepower: 283,
    maxhorsepowerat: 6400,
    maxtorque: 260,
    maxtorqueat: 4400,
    aspiration: "Naturally Aspirated",
    mpgcity: 17,
    mpghwy: 25,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: 3600,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/SAj22hcpDMUmLTfZzgyHZtC5_-VyPbxzIIzqdNUSakzjkvhLz3_zbszySUnG5B0IexPQjTKjys4TLLR0k8dDq1tzPfKFALYK92A",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/showme.svg",
    carfaxalt: "Show Me the CARFAX Badge",
    carfaxoneowner: 0,
    carfaxownerstext: "3+ Owners",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner3.svg",
    carfaxusetext: "Personal Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_personal.svg",
    carfaxservicerecords: 9,
    carfaxaccidenttext: "No Accident or Damage Reported",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_noAccident.svg",
    carfaxsnapshotkey:
      "HnzPgV6eEqW8DqPdbnxc1g1FvAWqIken6RreIgp4n_0ShWkQ3pIC8pwXRXahkxXj__o3Nd9xQNkXT4RThhzjIcsqfJOnBssg4HA",
    autocheck: null,
    photocount: 66,
    notes:
      "Clean CARFAX. Odometer is 20682 miles below market average!\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2015 Chrysler Town \u0026 Country. This Touring Town \u0026 Country comes well equipped with Black/Light Graystone Leather.\u003cbr\u003e\u003cbr\u003eBrilliant Black Crystal Pearlcoat 2015 Chrysler Town \u0026 Country Touring 6-Speed Automatic V6\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2015 Chrysler Town \u0026 Country Touring",
    url: "/inventory/2015-chrysler-town-country-touring-2C4RC1BG5FR610022",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 9995,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 9995,
      loan_months: 60,
      interest_rate: 0.0749,
      interest_rate_formatted: 7.49,
      credit_tier: "AA",
      total_cost: 12013.91,
      total_interest: 2018.91,
      monthly_payment: 200.23,
    },
    features: [
      {name:"Automatic climate control"},
      {name:"Backup camera"},
      {name:"Bluetooth"},
      {name:"Fog lights"},
      {name:"Leather seats"},
      {name:"Rear A/C"},
      {name:"Satellite radio ready"},
      {name:"Side impact airbags"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267826/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267826/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267826/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267826/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267826/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267828/image-1.webp" },
    id: 267828,
    dealer_id: 219,
    vin: "5NPE34AB3FH167422",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14412",
    location: "lot",
    originalprice: 14995,
    price: 14995,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2015,
    make: "Hyundai",
    model: "Sonata",
    modelnumber: "28462F45",
    trim: "Limited 2.0T",
    series: "",
    body: "Sedan",
    condition: "Pre-owned",
    certified: 0,
    mileage: 84721,
    exteriorcolor: "Phantom Black",
    interiorcolor: "Gray",
    exteriorcolorstandard: "Black",
    interiorcolorstandard: "Gray",
    fuel: "Gasoline",
    transmission: "6-Speed Automatic with Shiftronic",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "2.0L 4-Cylinder DGI Turbocharged",
    displacement: 2,
    cylinders: 4,
    maxhorsepower: 245,
    maxhorsepowerat: 6000,
    maxtorque: 260,
    maxtorqueat: 1350,
    aspiration: "Turbo",
    mpgcity: 21,
    mpghwy: 31,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: null,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/dcn49byR5fqUk2bQSl6z7Nnb9mwKdhCbJ5WeTcUXBlf_nGydjh2Q85E83McCe8N-T0Q5BpiuVRlqI9KfO4W-eLxYKQQHcgQQ2j8",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/showme.svg",
    carfaxalt: "Show Me the CARFAX Badge",
    carfaxoneowner: 0,
    carfaxownerstext: "3+ Owners",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner3.svg",
    carfaxusetext: "Multiple Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_generic.svg",
    carfaxservicerecords: 13,
    carfaxaccidenttext: "Minor Damage",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_information.svg",
    carfaxsnapshotkey:
      "AeCUnMv1kNt7VA8VRYGvwC0J50b8MbQlvE7i7u-yUwGFgGydZ8O_1KYu166-UWq2hghWM5AruJJGhnb6p12-zy_P5eohyC5_WQg",
    autocheck: null,
    photocount: 13,
    notes:
      "Odometer is 13679 miles below market average!\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2015 Hyundai Sonata. This Limited 2.0T Sonata comes well equipped with Gray Leather.\u003cbr\u003e\u003cbr\u003ePhantom Black 2015 Hyundai Sonata Limited 2.0T 6-Speed Automatic with Shiftronic 2.0L 4-Cylinder DGI Turbocharged\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2015 Hyundai Sonata Limited 2.0T",
    url: "/inventory/2015-hyundai-sonata-limited-2.0t-5NPE34AB3FH167422",
    hot: 1,
    new: 0,
    finance: {
      vehicle_amount: 14995,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 14995,
      loan_months: 60,
      interest_rate: 0.0749,
      interest_rate_formatted: 7.49,
      credit_tier: "AA",
      total_cost: 18023.87,
      total_interest: 3028.87,
      monthly_payment: 300.4,
    },
    features: [
      {name: "Automatic climate control"},
      {name: "Backup camera"},
      {name: "Blind spot monitor"},
      {name: "Bluetooth"},
      {name: "Collision warning"},
      {name: "Cross traffic alert"},
      {name: "Hands-free liftgate"},
      {name: "Heated seats"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267828/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267828/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267828/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267828/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267828/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267827/image-1.webp" },
    id: 267827,
    dealer_id: 219,
    vin: "5TFRX5GNXKX163606",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14405",
    location: "lot",
    originalprice: 21995,
    price: 21995,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2019,
    make: "Toyota",
    model: "Tacoma",
    modelnumber: null,
    trim: "SR5",
    series: "",
    body: "Pickup truck",
    condition: "Pre-owned",
    certified: 0,
    mileage: 107674,
    exteriorcolor: "Super White",
    interiorcolor: "Gray",
    exteriorcolorstandard: "White",
    interiorcolorstandard: "Gray",
    fuel: "Gasoline",
    transmission: "6-Speed Automatic",
    transmissionstandard: "Automatic",
    drivetrain: "RWD",
    drivetrainstandard: "RWD",
    engine: "2.7L I4 DOHC 16V",
    displacement: 2.7,
    cylinders: 4,
    maxhorsepower: 159,
    maxhorsepowerat: 5200,
    maxtorque: 180,
    maxtorqueat: 3800,
    aspiration: "Naturally Aspirated",
    mpgcity: 20,
    mpghwy: 23,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: 3500,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/0ox5u-5nAAhq0eaEb_HRdl8YLtgTDmO_jgL3xTagGURPUXwG8qy8zhPlSTtWMK2OJ7b_lifvfbrkJH_F0Mt_mobpsBQQ5iK6IZc",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/1own.svg",
    carfaxalt: "Show Me the CARFAX 1-Owner Badge",
    carfaxoneowner: 1,
    carfaxownerstext: "CARFAX 1-Owner",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner1.svg",
    carfaxusetext: "Commercial Use",
    carfaxuseicon:
      "https://partnerstatic.carfax.com/img/vhr/ico_commercial.svg",
    carfaxservicerecords: 23,
    carfaxaccidenttext: "No Accident or Damage Reported",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_noAccident.svg",
    carfaxsnapshotkey:
      "-JoL4cgFr3xcJzotVZUbzMd3clt6Q10Uh8bR6_eXc37Xes3fRdO5e0i2BswKrYajuH1EqxkC2dXcnXMjio_QmesLcujzsmsqflY",
    autocheck: null,
    photocount: 58,
    notes:
      "Clean CARFAX. CARFAX One-Owner.\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2019 Toyota Tacoma. This SR5 Tacoma comes well equipped with .\u003cbr\u003e\u003cbr\u003eSuper White 2019 Toyota Tacoma SR5 6-Speed Automatic 2.7L I4 DOHC 16V\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2019 Toyota Tacoma SR5",
    url: "/inventory/2019-toyota-tacoma-sr5-5TFRX5GNXKX163606",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 21995,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 21995,
      loan_months: 60,
      interest_rate: 0.0689,
      interest_rate_formatted: 6.89,
      credit_tier: "AA",
      total_cost: 26063.21,
      total_interest: 4068.21,
      monthly_payment: 434.39,
    },
    features: [
      {name:"Adaptive cruise control"},
      {name:"Backup camera"},
      {name:"Bluetooth"},
      {name:"Collision warning"},
      {name:"Fog lights"},
      {name:"Lane departure warning"},
      {name:"Satellite radio ready"},
      {name:"Side impact airbags"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267827/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267827/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267827/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267827/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267827/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267829/image-1.webp" },
    id: 267829,
    dealer_id: 219,
    vin: "5YFEPRAE1LP060511",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14385",
    location: "lot",
    originalprice: 15795,
    price: 15795,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2020,
    make: "Toyota",
    model: "Corolla",
    modelnumber: "1852",
    trim: "LE",
    series: "",
    body: "Sedan",
    condition: "Pre-owned",
    certified: 0,
    mileage: 91431,
    exteriorcolor: "Super White",
    interiorcolor: "Gray",
    exteriorcolorstandard: "White",
    interiorcolorstandard: "Gray",
    fuel: "Gasoline",
    transmission: "CVT",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "1.8L I4 DOHC 16V",
    displacement: 1.8,
    cylinders: 4,
    maxhorsepower: 139,
    maxhorsepowerat: 6100,
    maxtorque: 126,
    maxtorqueat: 3900,
    aspiration: "Naturally Aspirated",
    mpgcity: 30,
    mpghwy: 38,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: null,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/XJU-cJdNcExG5wvypL9_nrDWzrTD74E6mzbLQCBW0oqbpPEWK2R2XRrr_ADriTK9wLC1-IKAZkS25L_B-qJroSZtIQWVSWyWYdI",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/1own.svg",
    carfaxalt: "Show Me the CARFAX 1-Owner Badge",
    carfaxoneowner: 1,
    carfaxownerstext: "CARFAX 1-Owner",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner1.svg",
    carfaxusetext: "Commercial Use",
    carfaxuseicon:
      "https://partnerstatic.carfax.com/img/vhr/ico_commercial.svg",
    carfaxservicerecords: 16,
    carfaxaccidenttext: "No Accident or Damage Reported",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_noAccident.svg",
    carfaxsnapshotkey:
      "3APlJzwD6PBvOZ_-MjOe8Gf9Z92ETVgN_jE2yR_KdxJAbRb9VoyWYvwjWOtxgRphI_ozJMEmqcbrc4Zbn2eVBOuhM3aNuwhdA7o",
    autocheck: null,
    photocount: 64,
    notes:
      "Clean CARFAX. CARFAX One-Owner.\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2020 Toyota Corolla. This LE Corolla comes well equipped with .\u003cbr\u003e\u003cbr\u003eSuper White 2020 Toyota Corolla LE CVT 1.8L I4 DOHC 16V\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2020 Toyota Corolla LE",
    url: "/inventory/2020-toyota-corolla-le-5YFEPRAE1LP060511",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 15795,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 15795,
      loan_months: 60,
      interest_rate: 0.0649,
      interest_rate_formatted: 6.49,
      credit_tier: "AA",
      total_cost: 18538.4,
      total_interest: 2743.4,
      monthly_payment: 308.97,
    },
    features: [
      {name:"Adaptive cruise control"},
      {name:"Apple CarPlay"},
      {name:"Automatic climate control"},
      {name:"Backup camera"},
      {name:"Bluetooth"},
      {name:"Collision warning"},
      {name:"Lane departure warning"},
      {name:"Lane keep assist"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267829/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267829/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267829/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267829/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267829/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267825/image-1.webp" },
    id: 267825,
    dealer_id: 219,
    vin: "2T3RFREV8JW811122",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14275",
    location: "lot",
    originalprice: 19495,
    price: 19495,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2018,
    make: "Toyota",
    model: "RAV4",
    modelnumber: null,
    trim: "XLE",
    series: "",
    body: "SUV",
    condition: "Pre-owned",
    certified: 0,
    mileage: 94429,
    exteriorcolor: "Super White",
    interiorcolor: "Black",
    exteriorcolorstandard: "White",
    interiorcolorstandard: "Black",
    fuel: "Gasoline",
    transmission: "6-Speed Automatic",
    transmissionstandard: "Automatic",
    drivetrain: "AWD",
    drivetrainstandard: "AWD",
    engine: "2.5L 4-Cylinder DOHC Dual VVT-i",
    displacement: 2.5,
    cylinders: 4,
    maxhorsepower: 176,
    maxhorsepowerat: 6000,
    maxtorque: 172,
    maxtorqueat: 4100,
    aspiration: "Naturally Aspirated",
    mpgcity: 22,
    mpghwy: 28,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: 1500,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/Xc8u1-E90cejXB3uGLGHu2rLOi3fznDQRnFGUfMmaT_rIxlePGSJxj3W-XpIhq0eGQ4jAeXVgc1chWOXIDxf9mFwRgZexw7smPs",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/showme.svg",
    carfaxalt: "Show Me the CARFAX Badge",
    carfaxoneowner: 0,
    carfaxownerstext: "2-Owner",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner2.svg",
    carfaxusetext: "Multiple Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_generic.svg",
    carfaxservicerecords: 8,
    carfaxaccidenttext: "Accident/Minor Damage",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_orangeCar.svg",
    carfaxsnapshotkey:
      "qLxJbfegHp4vHP3NYtR2fAMtiXYUKyeNXbEfyJJEfdgJ1IY03_qS5PegR73Q2yZyv7p9FeUIZpD-had7NUQAx_p5FnuVIGNkb_s",
    autocheck: null,
    photocount: 61,
    notes:
      "Autos Direct is pleased to offer this Beautiful 2018 Toyota RAV4. This XLE RAV4 comes well equipped with AWD and Black Cloth.\u003cbr\u003e\u003cbr\u003eSuper White 2018 Toyota RAV4 XLE 6-Speed Automatic 2.5L 4-Cylinder DOHC Dual VVT-i\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2018 Toyota RAV4 XLE",
    url: "/inventory/2018-toyota-rav4-xle-2T3RFREV8JW811122",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 19495,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 19495,
      loan_months: 60,
      interest_rate: 0.0689,
      interest_rate_formatted: 6.89,
      credit_tier: "AA",
      total_cost: 23100.8,
      total_interest: 3605.8,
      monthly_payment: 385.01,
    },
    features: [
      {name:"Adaptive cruise control"},
      {name:"Automatic climate control"},
      {name:"Backup camera"},
      {name:"Bluetooth"},
      {name:"Collision warning"},
      {name:"Fog lights"},
      {name:"Lane departure warning"},
      {name:"Lane keep assist"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267825/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267825/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267825/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267825/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267825/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267824/image-1.webp" },
    id: 267824,
    dealer_id: 219,
    vin: "5FNRL6H97KB029469",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14468",
    location: "lot",
    originalprice: 26995,
    price: 26995,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2019,
    make: "Honda",
    model: "Odyssey",
    modelnumber: "RL6H9KKXW",
    trim: "Elite",
    series: "",
    body: "Passenger van",
    condition: "Pre-owned",
    certified: 0,
    mileage: 102084,
    exteriorcolor: "Modern Steel Metallic",
    interiorcolor: "Gray",
    exteriorcolorstandard: "Gray",
    interiorcolorstandard: "Gray",
    fuel: "Gasoline",
    transmission: "10-Speed Automatic",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "3.5L V6 SOHC i-VTEC 24V",
    displacement: 3.5,
    cylinders: 6,
    maxhorsepower: 280,
    maxhorsepowerat: 6000,
    maxtorque: 262,
    maxtorqueat: 4700,
    aspiration: "Naturally Aspirated",
    mpgcity: 19,
    mpghwy: 28,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: 3500,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/Quj20UnylN1B3IytT7PrYtKIq6DIWMc7wwc0WjbN0pbPn2biS7FADDYfLTlkVSY9qFQjHPliY86W_QUTeB0-nhBsIsGGpEcLDmQ",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/showme.svg",
    carfaxalt: "Show Me the CARFAX Badge",
    carfaxoneowner: 0,
    carfaxownerstext: "3+ Owners",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner3.svg",
    carfaxusetext: "Multiple Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_generic.svg",
    carfaxservicerecords: 14,
    carfaxaccidenttext: "Minor Damage",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_information.svg",
    carfaxsnapshotkey:
      "DJGo06CI4-rYX_zeEvyKAamWQSopRkFS5EVeRP92gaXwDzESS7TFboyYO0w5qGSedO6AO1AKj6gA_p-RixpCZC8K93uBachqgi0",
    autocheck: null,
    photocount: 75,
    notes:
      "Autos Direct is pleased to offer this Beautiful 2019 Honda Odyssey. This Elite Odyssey comes well equipped with .\u003cbr\u003e\u003cbr\u003eModern Steel 2019 Honda Odyssey Elite 10-Speed Automatic 3.5L V6 SOHC i-VTEC 24V\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2019 Honda Odyssey Elite",
    url: "/inventory/2019-honda-odyssey-elite-5FNRL6H97KB029469",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 26995,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 26995,
      loan_months: 60,
      interest_rate: 0.0689,
      interest_rate_formatted: 6.89,
      credit_tier: "AA",
      total_cost: 31988.01,
      total_interest: 4993.01,
      monthly_payment: 533.13,
    },
    features: [
      {name:"Adaptive cruise control"},
      {name:"Android Auto"},
      {name:"Apple CarPlay"},
      {name:"Automatic climate control"},
      {name:"Backup camera"},
      {name:"Blind spot monitor"},
      {name:"Bluetooth"},
      {name:"Collision warning"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267824/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267824/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267824/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267824/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267824/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267823/image-1.webp" },
    id: 267823,
    dealer_id: 219,
    vin: "5UXWX9C52H0T01719",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D13823",
    location: "lot",
    originalprice: 14495,
    price: 14495,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2017,
    make: "BMW",
    model: "X3",
    modelnumber: "17XD",
    trim: "xDrive28i",
    series: "",
    body: "SUV",
    condition: "Pre-owned",
    certified: 0,
    mileage: 78122,
    exteriorcolor: "Glacier Silver Metallic",
    interiorcolor: "Black",
    exteriorcolorstandard: "Silver",
    interiorcolorstandard: "Black",
    fuel: "Gasoline",
    transmission: "8-Speed Automatic",
    transmissionstandard: "Automatic",
    drivetrain: "AWD",
    drivetrainstandard: "AWD",
    engine: "2.0L I4 TwinPower Turbo",
    displacement: 2,
    cylinders: 4,
    maxhorsepower: 240,
    maxhorsepowerat: 5000,
    maxtorque: 260,
    maxtorqueat: 1450,
    aspiration: "Turbo",
    mpgcity: 21,
    mpghwy: 28,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: 3500,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/vunvZKYuSnUrj0fkj4nE_g24r7CoYG93N-UT1n77xhhTPESqt5loVDSHm5qpNMEvPvTc9qwVGYSleOKeJGXprbEA0VYAsXnjJig",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/showme.svg",
    carfaxalt: "Show Me the CARFAX Badge",
    carfaxoneowner: 0,
    carfaxownerstext: "3+ Owners",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner3.svg",
    carfaxusetext: "Multiple Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_generic.svg",
    carfaxservicerecords: 13,
    carfaxaccidenttext: "Minor Damage",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_information.svg",
    carfaxsnapshotkey:
      "BdZvUKSaIsNmAdKHikugbrvxOjzeMd93_4LgSS6P5qIhpl4q7t_I5EisZhsmstrmaxdu2RcCCPQlnjMM0gJwdyMnbb07ekliAiQ",
    autocheck: null,
    photocount: 73,
    notes:
      "Priced below KBB Fair Purchase Price! Odometer is 6840 miles below market average!\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2017 BMW X3. This xDrive28i X3 comes well equipped with 8-Speed Automatic.\u003cbr\u003e\u003cbr\u003eGlacier Silver Metallic 2017 BMW X3 xDrive28i 8-Speed Automatic 2.0L I4 TwinPower Turbo\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2017 BMW X3 xDrive28i",
    url: "/inventory/2017-bmw-x3-xdrive28i-5UXWX9C52H0T01719",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 14495,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 14495,
      loan_months: 60,
      interest_rate: 0.0749,
      interest_rate_formatted: 7.49,
      credit_tier: "AA",
      total_cost: 17422.87,
      total_interest: 2927.87,
      monthly_payment: 290.38,
    },
    features: [
      {name:"Automatic climate control"},
      {name:"Bluetooth"},
      {name:"Memory seats"},
      {name:"Push start"},
      {name:"Rain sensing wipers"},
      {name:"Satellite radio ready"},
      {name:"Side impact airbags"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267823/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267823/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267823/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267823/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267823/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267822/image-1.webp" },
    id: 267822,
    dealer_id: 219,
    vin: "1HGCV1F35JA087235",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14448",
    location: "lot",
    originalprice: 17995,
    price: 17995,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2018,
    make: "Honda",
    model: "Accord",
    modelnumber: "CV1F3JEW",
    trim: "Sport",
    series: "",
    body: "Sedan",
    condition: "Pre-owned",
    certified: 0,
    mileage: 118801,
    exteriorcolor: "Modern Steel Metallic",
    interiorcolor: "Black C",
    exteriorcolorstandard: "Gray",
    interiorcolorstandard: "Black",
    fuel: "Gasoline",
    transmission: "CVT",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "1.5T I4 DOHC 16V Turbocharged VTEC",
    displacement: 1.5,
    cylinders: 4,
    maxhorsepower: 192,
    maxhorsepowerat: 5500,
    maxtorque: 192,
    maxtorqueat: 1600,
    aspiration: "Turbo",
    mpgcity: 29,
    mpghwy: 35,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: null,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/zDgkqffpVSiOpR65I6oSqL_LchUoZK3xUuysXkH_t6dlmNifMACVLj2Jz-qGR7snDpIIocM3Zcu3sJ3rFwYmapEqrYnV1Gg4i4I",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/showme.svg",
    carfaxalt: "Show Me the CARFAX Badge",
    carfaxoneowner: 0,
    carfaxownerstext: "2-Owner",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner2.svg",
    carfaxusetext: "Personal Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_personal.svg",
    carfaxservicerecords: 15,
    carfaxaccidenttext: "No Accident or Damage Reported",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_noAccident.svg",
    carfaxsnapshotkey:
      "cy-W_TCBNwDC4ydT95dnQgC5alOwznxYxBt-NSrrOKAQ8uvGE6frrleg9VARpLaFFT6nQ_pAK3u_XDpGysKXeeKu8tyrZKaj0Os",
    autocheck: null,
    photocount: 67,
    notes:
      "Autos Direct is pleased to offer this Beautiful 2018 Honda Accord. This Sport Accord comes well equipped with Black C Artificial Leather.\u003cbr\u003e\u003cbr\u003eModern Steel 2018 Honda Accord Sport CVT 1.5T I4 DOHC 16V Turbocharged VTEC\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2018 Honda Accord Sport",
    url: "/inventory/2018-honda-accord-sport-1HGCV1F35JA087235",
    hot: 1,
    new: 0,
    finance: {
      vehicle_amount: 17995,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 17995,
      loan_months: 60,
      interest_rate: 0.0689,
      interest_rate_formatted: 6.89,
      credit_tier: "AA",
      total_cost: 21323.36,
      total_interest: 3328.36,
      monthly_payment: 355.39,
    },
    features: [
      {name: "Adaptive cruise control"},
      {name: "Android Auto"},
      {name: "Apple CarPlay"},
      {name: "Automatic climate control"},
      {name: "Backup camera"},
      {name: "Bluetooth"},
      {name: "Collision warning"},
      {name: "Lane departure warning"},
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267822/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267822/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267822/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267822/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267822/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267821/image-1.webp" },
    id: 267821,
    dealer_id: 219,
    vin: "ML32FUFJ8PHF03100",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14319",
    location: "lot",
    originalprice: 13495,
    price: 13495,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2023,
    make: "Mitsubishi",
    model: "Mirage G4",
    modelnumber: "MG41-E",
    trim: "LE",
    series: "",
    body: "Sedan",
    condition: "Pre-owned",
    certified: 0,
    mileage: 25905,
    exteriorcolor: "Mystic Black Metallic",
    interiorcolor: "Gray",
    exteriorcolorstandard: "Black",
    interiorcolorstandard: "Gray",
    fuel: "Gasoline",
    transmission: "CVT",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "1.2L 3-Cylinder DOHC MIVEC",
    displacement: 1.2,
    cylinders: 3,
    maxhorsepower: 78,
    maxhorsepowerat: 6000,
    maxtorque: 74,
    maxtorqueat: 4000,
    aspiration: "Naturally Aspirated",
    mpgcity: 35,
    mpghwy: 41,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: null,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/p79Q9KtvXYn3_buQ4y754eCUEOaGGdYMidPhj6Mu6H6XDcaRgkfraMHYQGCy2qnK2UIYIKdYhynvY3rZk_x6ri3BcL7qT8ITruk",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/1own.svg",
    carfaxalt: "Show Me the CARFAX 1-Owner Badge",
    carfaxoneowner: 1,
    carfaxownerstext: "CARFAX 1-Owner",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner1.svg",
    carfaxusetext: "Personal Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_personal.svg",
    carfaxservicerecords: 4,
    carfaxaccidenttext: "Major Damage",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_alert.svg",
    carfaxsnapshotkey:
      "elCBa_Yvinc7jyFfcTr1EjPyMI-_-Pg8Rj0t4vhoEF6s3qUf1ri6aX1byRqd9bECxQiikC88F_OIAgUXO46ogLxhJV1KDv28KPQ",
    autocheck: null,
    photocount: 64,
    notes:
      "CARFAX One-Owner. Priced below KBB Fair Purchase Price!\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2023 Mitsubishi Mirage G4. This LE Mirage G4 comes well equipped with .\u003cbr\u003e\u003cbr\u003eMystic Black 2023 Mitsubishi Mirage G4 LE CVT 1.2L 3-Cylinder DOHC MIVEC\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2023 Mitsubishi Mirage G4 LE",
    url: "/inventory/2023-mitsubishi-mirage-g4-le-ML32FUFJ8PHF03100",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 13495,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 13495,
      loan_months: 60,
      interest_rate: 0.0649,
      interest_rate_formatted: 6.49,
      credit_tier: "AA",
      total_cost: 15838.92,
      total_interest: 2343.92,
      monthly_payment: 263.98,
    },
    features: [
      "Android Auto",
      "Apple CarPlay",
      "Automatic climate control",
      "Backup camera",
      "Bluetooth",
      "Collision warning",
      "Fog lights",
      "Side impact airbags",
    ],
    photos: [
      { src: "https://static.overfuel.com/photos/219/267821/image-1-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267821/image-2-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267821/image-3-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267821/image-4-thumb.webp" },
      { src: "https://static.overfuel.com/photos/219/267821/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
  {
    featuredphoto: { src: "https://static.overfuel.com/photos/219/267819/image-1.webp" },
    id: 267819,
    dealer_id: 219,
    vin: "3FA6P0H75LR194395",
    status: "active",
    statusoverride: "",
    featured: 0,
    stocknumber: "D14398",
    location: "lot",
    originalprice: 13995,
    price: 13995,
    specialprice: 0,
    addonprice: 0,
    msrp: null,
    year: 2020,
    make: "Ford",
    model: "Fusion",
    modelnumber: "P0H",
    trim: "SE",
    series: "",
    body: "Sedan",
    condition: "Pre-owned",
    certified: 0,
    mileage: 102742,
    exteriorcolor: "White Platinum Metallic Tri-Coat",
    interiorcolor: "Ebony",
    exteriorcolorstandard: "White",
    interiorcolorstandard: "Black",
    fuel: "Gasoline",
    transmission: "6-Speed Automatic",
    transmissionstandard: "Automatic",
    drivetrain: "FWD",
    drivetrainstandard: "FWD",
    engine: "2.5L iVCT",
    displacement: 2.5,
    cylinders: 4,
    maxhorsepower: 175,
    maxhorsepowerat: 6000,
    maxtorque: 175,
    maxtorqueat: 4500,
    aspiration: "Naturally Aspirated",
    mpgcity: 21,
    mpghwy: 31,
    doors: 4,
    seatingcapacity: null,
    towingcapacity: null,
    carfaxurl:
      "https://www.carfax.com/VehicleHistory/ar20/8SvlzdvMMJDgdk1pYNvqEKSjedIPx6AjK65Vz_zCfVcfFF8tAlM3WRqgGxMCwbARVDniY6JKtSIbjA0dbde2YT0UdvlhHfGCFDM",
    carfaxicon: "https://partnerstatic.carfax.com/img/valuebadge/1own.svg",
    carfaxalt: "Show Me the CARFAX 1-Owner Badge",
    carfaxoneowner: 1,
    carfaxownerstext: "CARFAX 1-Owner",
    carfaxownersicon: "https://partnerstatic.carfax.com/img/vhr/ico_owner1.svg",
    carfaxusetext: "Corporate Use",
    carfaxuseicon: "https://partnerstatic.carfax.com/img/vhr/ico_corporate.svg",
    carfaxservicerecords: 1,
    carfaxaccidenttext: "No Accident or Damage Reported",
    carfaxaccidenticon:
      "https://partnerstatic.carfax.com/img/vhr/ico_noAccident.svg",
    carfaxsnapshotkey:
      "eJxbt5nYufXrzmkgpnygBD99s99I-1obayix8aHICxtLwJ3EOwm34sD9YTYWZleEFxcdaWxKwnvXVdR1ZjPqI5Fg5V1ECUjDCBE",
    autocheck: null,
    photocount: 66,
    notes:
      "Clean CARFAX. CARFAX One-Owner.\u003cbr\u003e\u003cbr\u003eAutos Direct is pleased to offer this Beautiful 2020 Ford Fusion. This SE Fusion comes well equipped with 6-Speed Automatic.\u003cbr\u003e\u003cbr\u003eWhite Platinum 2020 Ford Fusion SE 6-Speed Automatic 2.5L iVCT\u003cbr\u003e\u003cbr\u003ePlease print special internet price advertised on this site to guarantee online sales price. Must be presented at time of sale. Please call to check on the availability of this vehicle.All prices are plus tax, tag and fees. Shop 24/7 @ www.autosdirectva.com.",
    incentives: null,
    metatitle: null,
    metadescription: null,
    vehicledescription: null,
    dealer: {
      name: "Autos Direct Manassas",
      city: "Manassas",
      state: "VA",
      phonemain: "7032608338",
      capitalone_token: "3a39a4cf-ee72-407e-99c9-2cb2591f10d2",
    },
    title: "2020 Ford Fusion SE",
    url: "/inventory/2020-ford-fusion-se-3FA6P0H75LR194395",
    hot: 0,
    new: 0,
    finance: {
      vehicle_amount: 13995,
      shipping_amount: 0,
      tradein_amount: 0,
      tradein_remainingbalance: 0,
      down_payment: 0,
      doctitlefees_amount: 0,
      tax_amount: 0,
      tax_rate: null,
      tax_tradeincredit: null,
      loan_amount: 13995,
      loan_months: 60,
      interest_rate: 0.0649,
      interest_rate_formatted: 6.49,
      credit_tier: "AA",
      total_cost: 16425.76,
      total_interest: 2430.76,
      monthly_payment: 273.76,
    },
    features: [
      "Android Auto",
      "Apple CarPlay",
      "Automatic climate control",
      "Backup camera",
      "Blind spot monitor",
      "Bluetooth",
      "Collision warning",
      "Cross traffic alert",
    ],
    photos: [
      { src:  "https://static.overfuel.com/photos/219/267819/image-1-thumb.webp" },
      { src:  "https://static.overfuel.com/photos/219/267819/image-2-thumb.webp" },
      { src:  "https://static.overfuel.com/photos/219/267819/image-3-thumb.webp" },
      { src:  "https://static.overfuel.com/photos/219/267819/image-4-thumb.webp" },
      { src:  "https://static.overfuel.com/photos/219/267819/image-5-thumb.webp" },
    ],
    video: {
      source: null,
      url: null,
      autoplay: null,
      aspectratio: null,
    },
  },
];
